import type { Snapshot } from "./data";

export type ArchiveFile = {
  path: string;
  content: string;
};

async function sha256(data: string): Promise<string> {
  const { createHash } = await import("node:crypto");
  return createHash("sha256").update(data, "utf-8").digest("hex");
}

function padTo512(buf: Buffer): Buffer {
  const remainder = buf.length % 512;
  if (remainder === 0) return buf;
  const padded = Buffer.alloc(buf.length + (512 - remainder));
  buf.copy(padded);
  return padded;
}

function ustarHeader(path: string, size: number): Buffer {
  const header = Buffer.alloc(512, 0);
  const name = Buffer.from(path, "ascii");
  name.copy(header, 0, 0, Math.min(name.length, 100));
  const sizeOct = size.toString(8).padStart(11, "0");
  Buffer.from(sizeOct, "ascii").copy(header, 124, 0, 11);
  Buffer.from("0000644", "ascii").copy(header, 100, 0, 7);
  Buffer.from("0001750", "ascii").copy(header, 108, 0, 7);
  Buffer.from("0001750", "ascii").copy(header, 116, 0, 7);
  const mtime = Math.floor(Date.now() / 1000)
    .toString(8)
    .padStart(11, "0");
  Buffer.from(mtime, "ascii").copy(header, 136, 0, 11);
  header[156] = 48;
  Buffer.from("ustar\0", "ascii").copy(header, 257, 0, 6);
  Buffer.from("00", "ascii").copy(header, 263, 0, 2);
  let checksum = 0;
  for (let i = 0; i < 512; i++) checksum += header[i];
  const chksum = checksum.toString(8).padStart(6, "0");
  Buffer.from(chksum, "ascii").copy(header, 148, 0, 6);
  header[154] = 0x20;
  return header;
}

function buildTar(files: ArchiveFile[]): Buffer {
  const chunks: Buffer[] = [];
  for (const file of files) {
    const content = Buffer.from(file.content, "utf-8");
    chunks.push(ustarHeader(file.path, content.length));
    chunks.push(padTo512(content));
  }
  chunks.push(Buffer.alloc(1024, 0));
  return Buffer.concat(chunks);
}

export async function buildArchiveFiles(snapshot: Snapshot): Promise<ArchiveFile[]> {
  const isoDate = snapshot.isoDate;
  const snapshotJson = JSON.stringify(snapshot, null, 2);
  const snapshotHash = await sha256(snapshotJson);

  const manifest = {
    archive: "public-record-archive",
    format_version: 1,
    created: new Date().toISOString(),
    snapshot: {
      isoDate: snapshot.isoDate,
      date: snapshot.date,
      generated: snapshot.generated,
      articles: snapshot.articles,
      sources: snapshot.sources,
      countries: snapshot.countries,
      hash: snapshot.hash,
    },
    files: [
      { path: `${isoDate}/snapshot.json`, description: "Snapshot data" },
      { path: `${isoDate}/MANIFEST.json`, description: "Archive metadata manifest" },
      { path: `${isoDate}/SHA256SUMS`, description: "SHA-256 checksums for all files" },
      { path: `${isoDate}/README.md`, description: "Verification instructions" },
    ],
  };

  const manifestJson = JSON.stringify(manifest, null, 2);
  const manifestHash = await sha256(manifestJson);

  const readme = `# Public Internet Record — Snapshot Archive

Date: ${snapshot.date} (${snapshot.isoDate})
Records: ${snapshot.articles}
Sources: ${snapshot.sources}
Countries: ${snapshot.countries}
Root Hash: ${snapshot.hash}

## Files

This archive contains:

- \`snapshot.json\` — Full snapshot data including all records and metadata
- \`MANIFEST.json\` — Archive metadata and file listing
- \`SHA256SUMS\` — SHA-256 checksums for every file in this archive

## Offline Verification

To verify this archive was not tampered with:

    $ tar xzf public-record-${isoDate}.tar.gz
    $ cd ${isoDate}
    $ sha256sum --check SHA256SUMS
    $ sha256sum snapshot.json
    ${snapshot.hash}  snapshot.json

The root hash in MANIFEST.json should match the SHA-256 of the records array
in snapshot.json. Compute it with:

    $ node -e "const d=require('./snapshot.json'); const {createHash}=require('crypto');
      const h=createHash('sha256').update(JSON.stringify(d.records,null,2),'utf-8').digest('hex');
      console.log(h === '${snapshot.hash}' ? 'PASS' : 'FAIL');"

## Integrity

Every record in this snapshot has an individual SHA-256 hash. The snapshot's
root hash is the SHA-256 of the JSON-serialized records array. This is
verified client-side using the Web Crypto API at https://public-record.org.

For independent verification, use the commands above. No software other than
standard command-line tools (tar, sha256sum, node) is required.

---

Generated by the Public Internet Record archive system.
https://github.com/lacebx/the-public-record-archive
`;

  const shaLines = [
    `${snapshotHash}  ${isoDate}/snapshot.json`,
    `${manifestHash}  ${isoDate}/MANIFEST.json`,
  ];

  for (const file of [{ content: readme, path: `${isoDate}/README.md` }]) {
    const h = await sha256(file.content);
    shaLines.push(`${h}  ${file.path}`);
  }

  shaLines.push("");

  return [
    { path: `${isoDate}/snapshot.json`, content: snapshotJson },
    { path: `${isoDate}/MANIFEST.json`, content: manifestJson },
    { path: `${isoDate}/SHA256SUMS`, content: shaLines.join("\n") },
    { path: `${isoDate}/README.md`, content: readme },
  ];
}

export async function buildArchiveTarGz(snapshot: Snapshot): Promise<Buffer> {
  const files = await buildArchiveFiles(snapshot);
  const tar = buildTar(files);
  const { gzipSync } = await import("node:zlib");
  return gzipSync(tar);
}

export function archiveFilename(isoDate: string): string {
  return `public-record-${isoDate}.tar.gz`;
}
