import { createServerFn } from "@tanstack/react-start";

// snapshot-data.ts is auto-generated by scripts/generate-snapshot.ts
// It is bundled at build time so no filesystem access is needed at runtime.
import bundledSnapshot from "./snapshot-data";

export type Record = {
  id: string;
  publisher: string;
  title: string;
  published: string;
  archived: string;
  status: "VERIFIED" | "PENDING";
  hash: string;
  summary: string;
  sourceUrl: string;
  country: string;
  category: string;
};

export type Snapshot = {
  date: string;
  isoDate: string;
  generated: string;
  articles: number;
  sources: number;
  countries: number;
  status: string;
  hash: string;
  records: Record[];
};

export const getSnapshot = createServerFn({ method: "GET" }).handler(
  // @ts-expect-error - compiled by babel plugin
  async () => bundledSnapshot satisfies Snapshot,
);

export const getSnapshotByDate = createServerFn({ method: "GET" }).handler(
  // @ts-expect-error - compiled by babel plugin
  async (date: string) => {
    if (date === bundledSnapshot.isoDate) return bundledSnapshot satisfies Snapshot;
    return null;
  },
);
